/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <Foundation/Foundation.h>
#import "CelebritiesModel.h"
#import "ImageMetadata.h"

/**
 * List of celebrities recognized in the image.
*/
@interface CelebrityResults : NSObject

    /**
     * The celebrities property.
    */
    // json value = "celebrities"
    @property NSArray<CelebritiesModel*> * celebrities;

    /**
     * Id of the REST API request.
    */
    // json value = "requestId"
    @property NSString* requestId;

    /**
     * The metadata property.
    */
    // json value = "metadata"
    @property ImageMetadata* metadata;


@end
