/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import <Foundation/Foundation.h>

/**
 * Defines values for Details.
 */
@interface Details : NSString

    + (NSArray<Details*> *) enumerate;

    + (Details *) fromString: (NSString *) string;

    + (NSString *) toStringValue: (Details *) value;

    @property (class, readonly) Details* CELEBRITIES;

    @property (class, readonly) Details* LANDMARKS;

@end
