/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "ImageUrl.h"

@implementation ImageUrl

    - (id) initUrl: (NSString*) url {
        self = [super init];
        if (self) {
            _url = url;
        }
        return self;
    }

@end
