/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <Foundation/Foundation.h>

/**
 * An image caption, i.e. a brief description of what the image depicts.
*/
@interface ImageCaption : NSObject

    /**
     * The text of the caption.
    */
    // json value = "text"
    @property NSString* text;

    /**
     * The level of confidence the service has in the caption.
    */
    // json value = "confidence"
    @property double confidence;


@end
