/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <Foundation/Foundation.h>
#import "ImageCaption.h"

/**
 * A collection of content tags, along with a list of captions sorted by
 * confidence level, and image metadata.
*/
@interface ImageDescriptionDetails : NSObject

    /**
     * A collection of image tags.
    */
    // json value = "tags"
    @property NSArray<NSString*> * tags;

    /**
     * A list of captions, sorted by confidence level.
    */
    // json value = "captions"
    @property NSArray<ImageCaption*> * captions;


@end
