/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <Foundation/Foundation.h>

/**
 * The ImageUrl model.
*/
@interface ImageUrl : NSObject

    /**
     * Publicly reachable URL of an image.
    */
    // json value = "url", required = true
    @property NSString* url;

    /**
    * Creates an instance of ImageUrl class.
    * @param url publicly reachable URL of an image.
    */
    - (id) initUrl: (NSString*) url;


@end
