/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <Foundation/Foundation.h>

/**
 * Image metadata.
*/
@interface ImageMetadata : NSObject

    /**
     * Image width.
    */
    // json value = "width"
    @property int width;

    /**
     * Image height.
    */
    // json value = "height"
    @property int height;

    /**
     * Image format.
    */
    // json value = "format"
    @property NSString* format;


@end
