/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <Foundation/Foundation.h>

/**
 * An image caption, i.e. a brief description of what the image depicts.
*/
@interface ImageTag : NSObject

    /**
     * The tag value.
    */
    // json value = "name"
    @property NSString* name;

    /**
     * The level of confidence the service has in the caption.
    */
    // json value = "confidence"
    @property double confidence;

    /**
     * Optional categorization for the tag.
    */
    // json value = "hint"
    @property NSString* hint;


@end
