/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <Foundation/Foundation.h>
#import "ImageCaption.h"
#import "ImageMetadata.h"

/**
 * A collection of content tags, along with a list of captions sorted by
 * confidence level, and image metadata.
*/
// Needs Flatten
@interface ImageDescription : NSObject

    /**
     * A collection of image tags.
    */
    // json value = "description.tags"
    @property NSArray<NSString*> * tags;

    /**
     * A list of captions, sorted by confidence level.
    */
    // json value = "description.captions"
    @property NSArray<ImageCaption*> * captions;

    /**
     * Id of the REST API request.
    */
    // json value = "requestId"
    @property NSString* requestId;

    /**
     * The metadata property.
    */
    // json value = "metadata"
    @property ImageMetadata* metadata;


@end
