/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <Foundation/Foundation.h>
#import "LandmarksModel.h"
#import "ImageMetadata.h"

/**
 * List of landmarks recognized in the image.
*/
@interface LandmarkResults : NSObject

    /**
     * The landmarks property.
    */
    // json value = "landmarks"
    @property NSArray<LandmarksModel*> * landmarks;

    /**
     * Id of the REST API request.
    */
    // json value = "requestId"
    @property NSString* requestId;

    /**
     * The metadata property.
    */
    // json value = "metadata"
    @property ImageMetadata* metadata;


@end
