/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <Foundation/Foundation.h>

/**
 * An object describing supported model by name and categories.
*/
@interface ModelDescription : NSObject

    /**
     * The name property.
    */
    // json value = "name"
    @property NSString* name;

    /**
     * The categories property.
    */
    // json value = "categories"
    @property NSArray<NSString*> * categories;


@end
