/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <Foundation/Foundation.h>
#import "OcrWord.h"

/**
 * An object describing a single recognized line of text.
*/
@interface OcrLine : NSObject

    /**
     * Bounding box of a recognized line. The four integers represent the
     * x-coordinate of the left edge, the y-coordinate of the top edge, width,
     * and height of the bounding box, in the coordinate system of the input
     * image, after it has been rotated around its center according to the
     * detected text angle (see textAngle property), with the origin at the
     * top-left corner, and the y-axis pointing down.
    */
    // json value = "boundingBox"
    @property NSString* boundingBox;

    /**
     * An array of objects, where each object represents a recognized word.
    */
    // json value = "words"
    @property NSArray<OcrWord*> * words;


@end
