/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import <Foundation/Foundation.h>

/**
 * Defines values for OcrLanguages.
 */
@interface OcrLanguages : NSString

    + (NSArray<OcrLanguages*> *) enumerate;

    + (OcrLanguages *) fromString: (NSString *) string;

    + (NSString *) toStringValue: (OcrLanguages *) value;

    @property (class, readonly) OcrLanguages* UNK;

    @property (class, readonly) OcrLanguages* ZH_HANS;

    @property (class, readonly) OcrLanguages* ZH_HANT;

    @property (class, readonly) OcrLanguages* CS;

    @property (class, readonly) OcrLanguages* DA;

    @property (class, readonly) OcrLanguages* NL;

    @property (class, readonly) OcrLanguages* EN;

    @property (class, readonly) OcrLanguages* FI;

    @property (class, readonly) OcrLanguages* FR;

    @property (class, readonly) OcrLanguages* DE;

    @property (class, readonly) OcrLanguages* EL;

    @property (class, readonly) OcrLanguages* HU;

    @property (class, readonly) OcrLanguages* IT;

    @property (class, readonly) OcrLanguages* JA;

    @property (class, readonly) OcrLanguages* KO;

    @property (class, readonly) OcrLanguages* NB;

    @property (class, readonly) OcrLanguages* PL;

    @property (class, readonly) OcrLanguages* PT;

    @property (class, readonly) OcrLanguages* RU;

    @property (class, readonly) OcrLanguages* ES;

    @property (class, readonly) OcrLanguages* SV;

    @property (class, readonly) OcrLanguages* TR;

    @property (class, readonly) OcrLanguages* AR;

    @property (class, readonly) OcrLanguages* RO;

    @property (class, readonly) OcrLanguages* SR_CYRL;

    @property (class, readonly) OcrLanguages* SR_LATN;

    @property (class, readonly) OcrLanguages* SK;

@end
