/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import <Foundation/Foundation.h>

/**
 * Defines values for TextRecognitionMode.
 */
@interface TextRecognitionMode : NSString

    + (NSArray<TextRecognitionMode*> *) enumerate;

    + (TextRecognitionMode *) fromString: (NSString *) string;

    + (NSString *) toStringValue: (TextRecognitionMode *) value;

    @property (class, readonly) TextRecognitionMode* HANDWRITTEN;

    @property (class, readonly) TextRecognitionMode* PRINTED;

@end
