/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import <Foundation/Foundation.h>

/**
 * Defines values for TextOperationStatusCodes.
 */
@interface TextOperationStatusCodes : NSString

    + (NSArray<TextOperationStatusCodes*> *) enumerate;

    + (TextOperationStatusCodes *) fromString: (NSString *) string;

    + (NSString *) toStringValue: (TextOperationStatusCodes *) value;

    @property (class, readonly) TextOperationStatusCodes* NOT_STARTED;

    @property (class, readonly) TextOperationStatusCodes* RUNNING;

    @property (class, readonly) TextOperationStatusCodes* FAILED;

    @property (class, readonly) TextOperationStatusCodes* SUCCEEDED;

@end
