/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <Foundation/Foundation.h>
#import "TextOperationStatusCodes.h"
#import "RecognitionResult.h"

/**
 * The TextOperationResult model.
*/
@interface TextOperationResult : NSObject

    /**
     * Status of the text operation. Possible values include: 'Not Started',
     * 'Running', 'Failed', 'Succeeded'.
    */
    // json value = "status"
    @property TextOperationStatusCodes* status;

    /**
     * The recognitionResult property.
    */
    // json value = "recognitionResult"
    @property RecognitionResult* recognitionResult;


@end
