/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "VisualFeatureTypes.h"

/**
 * Defines values for VisualFeatureTypes.
 */
@implementation VisualFeatureTypes

    + (NSArray<VisualFeatureTypes*>*) enumerate {
        NSArray *array = @[
            @"ImageType",
            @"Faces",
            @"Adult",
            @"Categories",
            @"Color",
            @"Tags",
            @"Description"
        ];
        return array;
    }

    + (VisualFeatureTypes *) fromString: (NSString *) string {
        return (VisualFeatureTypes *) string;
    }

    + (NSString *) toStringValue: (VisualFeatureTypes *) value {
        return (NSString *) value;
    }

    /** Enum value ImageType. */
    static VisualFeatureTypes* _IMAGE_TYPE = (VisualFeatureTypes*)@"ImageType";

    + (VisualFeatureTypes*) IMAGE_TYPE {
        return _IMAGE_TYPE;
    }

    /** Enum value Faces. */
    static VisualFeatureTypes* _FACES = (VisualFeatureTypes*)@"Faces";

    + (VisualFeatureTypes*) FACES {
        return _FACES;
    }

    /** Enum value Adult. */
    static VisualFeatureTypes* _ADULT = (VisualFeatureTypes*)@"Adult";

    + (VisualFeatureTypes*) ADULT {
        return _ADULT;
    }

    /** Enum value Categories. */
    static VisualFeatureTypes* _CATEGORIES = (VisualFeatureTypes*)@"Categories";

    + (VisualFeatureTypes*) CATEGORIES {
        return _CATEGORIES;
    }

    /** Enum value Color. */
    static VisualFeatureTypes* _COLOR = (VisualFeatureTypes*)@"Color";

    + (VisualFeatureTypes*) COLOR {
        return _COLOR;
    }

    /** Enum value Tags. */
    static VisualFeatureTypes* _TAGS = (VisualFeatureTypes*)@"Tags";

    + (VisualFeatureTypes*) TAGS {
        return _TAGS;
    }

    /** Enum value Description. */
    static VisualFeatureTypes* _DESCRIPTION = (VisualFeatureTypes*)@"Description";

    + (VisualFeatureTypes*) DESCRIPTION {
        return _DESCRIPTION;
    }

@end
