/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <Foundation/Foundation.h>

/**
 * The Word model.
*/
@interface Word : NSObject

    /**
     * The boundingBox property.
    */
    // json value = "boundingBox"
    @property NSArray<NSNumber*> * boundingBox;

    /**
     * The text property.
    */
    // json value = "text"
    @property NSString* text;


@end
