/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <Foundation/Foundation.h>
#import "CategoryDetail.h"

/**
 * An object describing identified category.
*/
@interface Category : NSObject

    /**
     * Name of the category.
    */
    // json value = "name"
    @property NSString* name;

    /**
     * Scoring of the category.
    */
    // json value = "score"
    @property double score;

    /**
     * The detail property.
    */
    // json value = "detail"
    @property CategoryDetail* detail;


@end
