/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <Foundation/Foundation.h>
#import "CelebritiesModel.h"
#import "LandmarksModel.h"

/**
 * An object describing additional category details.
*/
@interface CategoryDetail : NSObject

    /**
     * An array of celebrities if any identified.
    */
    // json value = "celebrities"
    @property NSArray<CelebritiesModel*> * celebrities;

    /**
     * An array of landmarks if any identified.
    */
    // json value = "landmarks"
    @property NSArray<LandmarksModel*> * landmarks;


@end
