/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <Foundation/Foundation.h>
#import "FaceRectangle.h"

/**
 * An object describing possible celebrity identification.
*/
@interface CelebritiesModel : NSObject

    /**
     * Name of the celebrity.
    */
    // json value = "name"
    @property NSString* name;

    /**
     * Level of confidence ranging from 0 to 1.
    */
    // json value = "confidence"
    @property double confidence;

    /**
     * The faceRectangle property.
    */
    // json value = "faceRectangle"
    @property FaceRectangle* faceRectangle;


@end
