/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <Foundation/Foundation.h>

/**
 * An object providing additional metadata describing color attributes.
*/
@interface ColorInfo : NSObject

    /**
     * Possible dominant foreground color.
    */
    // json value = "dominantColorForeground"
    @property NSString* dominantColorForeground;

    /**
     * Possible dominant background color.
    */
    // json value = "dominantColorBackground"
    @property NSString* dominantColorBackground;

    /**
     * An array of possible dominant colors.
    */
    // json value = "dominantColors"
    @property NSArray<NSString*> * dominantColors;

    /**
     * Possible accent color.
    */
    // json value = "accentColor"
    @property NSString* accentColor;

    /**
     * A value indicating if the image is black and white.
    */
    // json value = "isBWImg"
    @property BOOL isBWImg;


@end
