/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "ComputerVisionError.h"

@implementation ComputerVisionError

    - (id) initCode: (ComputerVisionErrorCodes*) code message: (NSString*) message {
        self = [super init];
        if (self) {
            _code = code;
            _message = message;
        }
        return self;
    }

@end
