/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <Foundation/Foundation.h>
#import "ImageMetadata.h"

/**
 * Result of image analysis using a specific domain model including additional
 * metadata.
*/
@interface DomainModelResults : NSObject

    /**
     * Model-specific response.
    */
    // json value = "result"
    @property NSObject* result;

    /**
     * Id of the REST API request.
    */
    // json value = "requestId"
    @property NSString* requestId;

    /**
     * The metadata property.
    */
    // json value = "metadata"
    @property ImageMetadata* metadata;


@end
