/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <Foundation/Foundation.h>
#import "Gender.h"
#import "FaceRectangle.h"

/**
 * An object describing a face identified in the image.
*/
@interface FaceDescription : NSObject

    /**
     * Possible age of the face.
    */
    // json value = "age"
    @property int age;

    /**
     * Possible gender of the face. Possible values include: 'Male', 'Female'.
    */
    // json value = "gender"
    @property Gender* gender;

    /**
     * The faceRectangle property.
    */
    // json value = "faceRectangle"
    @property FaceRectangle* faceRectangle;


@end
