/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import <Foundation/Foundation.h>

/**
 * Defines values for Gender.
 */
@interface Gender : NSString

    + (NSArray<Gender*> *) enumerate;

    + (Gender *) fromString: (NSString *) string;

    + (NSString *) toStringValue: (Gender *) value;

    @property (class, readonly) Gender* MALE;

    @property (class, readonly) Gender* FEMALE;

@end
