/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <Foundation/Foundation.h>
#import "Category.h"
#import "AdultInfo.h"
#import "ColorInfo.h"
#import "ImageType.h"
#import "ImageTag.h"
#import "ImageDescriptionDetails.h"
#import "FaceDescription.h"
#import "ImageMetadata.h"

/**
 * Result of AnalyzeImage operation.
*/
@interface ImageAnalysis : NSObject

    /**
     * An array indicating identified categories.
    */
    // json value = "categories"
    @property NSArray<Category*> * categories;

    /**
     * The adult property.
    */
    // json value = "adult"
    @property AdultInfo* adult;

    /**
     * The color property.
    */
    // json value = "color"
    @property ColorInfo* color;

    /**
     * The imageType property.
    */
    // json value = "imageType"
    @property ImageType* imageType;

    /**
     * A list of tags with confidence level.
    */
    // json value = "tags"
    @property NSArray<ImageTag*> * tags;

    /**
     * The descriptionProperty property.
    */
    // json value = "description"
    @property ImageDescriptionDetails* descriptionProperty;

    /**
     * An array of possible faces within the image.
    */
    // json value = "faces"
    @property NSArray<FaceDescription*> * faces;

    /**
     * Id of the request for tracking purposes.
    */
    // json value = "requestId"
    @property NSString* requestId;

    /**
     * The metadata property.
    */
    // json value = "metadata"
    @property ImageMetadata* metadata;


@end
