/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <Foundation/Foundation.h>

/**
 * A landmark recognized in the image.
*/
@interface LandmarksModel : NSObject

    /**
     * Name of the landmark.
    */
    // json value = "name"
    @property NSString* name;

    /**
     * Confidence level for the landmark recognition.
    */
    // json value = "confidence"
    @property double confidence;


@end
