/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "OcrLanguages.h"

/**
 * Defines values for OcrLanguages.
 */
@implementation OcrLanguages

    + (NSArray<OcrLanguages*>*) enumerate {
        NSArray *array = @[
            @"unk",
            @"zh-Hans",
            @"zh-Hant",
            @"cs",
            @"da",
            @"nl",
            @"en",
            @"fi",
            @"fr",
            @"de",
            @"el",
            @"hu",
            @"it",
            @"ja",
            @"ko",
            @"nb",
            @"pl",
            @"pt",
            @"ru",
            @"es",
            @"sv",
            @"tr",
            @"ar",
            @"ro",
            @"sr-Cyrl",
            @"sr-Latn",
            @"sk"
        ];
        return array;
    }

    + (OcrLanguages *) fromString: (NSString *) string {
        return (OcrLanguages *) string;
    }

    + (NSString *) toStringValue: (OcrLanguages *) value {
        return (NSString *) value;
    }

    /** Enum value unk. */
    static OcrLanguages* _UNK = (OcrLanguages*)@"unk";

    + (OcrLanguages*) UNK {
        return _UNK;
    }

    /** Enum value zh-Hans. */
    static OcrLanguages* _ZH_HANS = (OcrLanguages*)@"zh-Hans";

    + (OcrLanguages*) ZH_HANS {
        return _ZH_HANS;
    }

    /** Enum value zh-Hant. */
    static OcrLanguages* _ZH_HANT = (OcrLanguages*)@"zh-Hant";

    + (OcrLanguages*) ZH_HANT {
        return _ZH_HANT;
    }

    /** Enum value cs. */
    static OcrLanguages* _CS = (OcrLanguages*)@"cs";

    + (OcrLanguages*) CS {
        return _CS;
    }

    /** Enum value da. */
    static OcrLanguages* _DA = (OcrLanguages*)@"da";

    + (OcrLanguages*) DA {
        return _DA;
    }

    /** Enum value nl. */
    static OcrLanguages* _NL = (OcrLanguages*)@"nl";

    + (OcrLanguages*) NL {
        return _NL;
    }

    /** Enum value en. */
    static OcrLanguages* _EN = (OcrLanguages*)@"en";

    + (OcrLanguages*) EN {
        return _EN;
    }

    /** Enum value fi. */
    static OcrLanguages* _FI = (OcrLanguages*)@"fi";

    + (OcrLanguages*) FI {
        return _FI;
    }

    /** Enum value fr. */
    static OcrLanguages* _FR = (OcrLanguages*)@"fr";

    + (OcrLanguages*) FR {
        return _FR;
    }

    /** Enum value de. */
    static OcrLanguages* _DE = (OcrLanguages*)@"de";

    + (OcrLanguages*) DE {
        return _DE;
    }

    /** Enum value el. */
    static OcrLanguages* _EL = (OcrLanguages*)@"el";

    + (OcrLanguages*) EL {
        return _EL;
    }

    /** Enum value hu. */
    static OcrLanguages* _HU = (OcrLanguages*)@"hu";

    + (OcrLanguages*) HU {
        return _HU;
    }

    /** Enum value it. */
    static OcrLanguages* _IT = (OcrLanguages*)@"it";

    + (OcrLanguages*) IT {
        return _IT;
    }

    /** Enum value ja. */
    static OcrLanguages* _JA = (OcrLanguages*)@"ja";

    + (OcrLanguages*) JA {
        return _JA;
    }

    /** Enum value ko. */
    static OcrLanguages* _KO = (OcrLanguages*)@"ko";

    + (OcrLanguages*) KO {
        return _KO;
    }

    /** Enum value nb. */
    static OcrLanguages* _NB = (OcrLanguages*)@"nb";

    + (OcrLanguages*) NB {
        return _NB;
    }

    /** Enum value pl. */
    static OcrLanguages* _PL = (OcrLanguages*)@"pl";

    + (OcrLanguages*) PL {
        return _PL;
    }

    /** Enum value pt. */
    static OcrLanguages* _PT = (OcrLanguages*)@"pt";

    + (OcrLanguages*) PT {
        return _PT;
    }

    /** Enum value ru. */
    static OcrLanguages* _RU = (OcrLanguages*)@"ru";

    + (OcrLanguages*) RU {
        return _RU;
    }

    /** Enum value es. */
    static OcrLanguages* _ES = (OcrLanguages*)@"es";

    + (OcrLanguages*) ES {
        return _ES;
    }

    /** Enum value sv. */
    static OcrLanguages* _SV = (OcrLanguages*)@"sv";

    + (OcrLanguages*) SV {
        return _SV;
    }

    /** Enum value tr. */
    static OcrLanguages* _TR = (OcrLanguages*)@"tr";

    + (OcrLanguages*) TR {
        return _TR;
    }

    /** Enum value ar. */
    static OcrLanguages* _AR = (OcrLanguages*)@"ar";

    + (OcrLanguages*) AR {
        return _AR;
    }

    /** Enum value ro. */
    static OcrLanguages* _RO = (OcrLanguages*)@"ro";

    + (OcrLanguages*) RO {
        return _RO;
    }

    /** Enum value sr-Cyrl. */
    static OcrLanguages* _SR_CYRL = (OcrLanguages*)@"sr-Cyrl";

    + (OcrLanguages*) SR_CYRL {
        return _SR_CYRL;
    }

    /** Enum value sr-Latn. */
    static OcrLanguages* _SR_LATN = (OcrLanguages*)@"sr-Latn";

    + (OcrLanguages*) SR_LATN {
        return _SR_LATN;
    }

    /** Enum value sk. */
    static OcrLanguages* _SK = (OcrLanguages*)@"sk";

    + (OcrLanguages*) SK {
        return _SK;
    }

@end
