/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <Foundation/Foundation.h>
#import "OcrRegion.h"

/**
 * The OcrResult model.
*/
@interface OcrResult : NSObject

    /**
     * The BCP-47 language code of the text in the image.
    */
    // json value = "language"
    @property NSString* language;

    /**
     * The angle, in degrees, of the detected text with respect to the closest
     * horizontal or vertical direction. After rotating the input image
     * clockwise by this angle, the recognized text lines become horizontal or
     * vertical. In combination with the orientation property it can be used to
     * overlay recognition results correctly on the original image, by rotating
     * either the original image or recognition results by a suitable angle
     * around the center of the original image. If the angle cannot be
     * confidently detected, this property is not present. If the image
     * contains text at different angles, only part of the text will be
     * recognized correctly.
    */
    // json value = "textAngle"
    @property double textAngle;

    /**
     * Orientation of the text recognized in the image. The value
     * (up,down,left, or right) refers to the direction that the top of the
     * recognized text is facing, after the image has been rotated around its
     * center according to the detected text angle (see textAngle property).
    */
    // json value = "orientation"
    @property NSString* orientation;

    /**
     * An array of objects, where each object represents a region of recognized
     * text.
    */
    // json value = "regions"
    @property NSArray<OcrRegion*> * regions;


@end
