/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <Foundation/Foundation.h>
#import "Line.h"

/**
 * The RecognitionResult model.
*/
@interface RecognitionResult : NSObject

    /**
     * The lines property.
    */
    // json value = "lines"
    @property NSArray<Line*> * lines;


@end
