/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <Foundation/Foundation.h>

/**
 * Defines headers for RecognizeTextInStream operation.
*/
@interface RecognizeTextInStreamHeaders : NSObject

    /**
     * URL to query for status of the operation. The operation ID will expire
     * in 48 hours.
    */
    // json value = "Operation-Location"
    @property NSString* operationLocation;


@end
