/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "TextOperationStatusCodes.h"

/**
 * Defines values for TextOperationStatusCodes.
 */
@implementation TextOperationStatusCodes

    + (NSArray<TextOperationStatusCodes*>*) enumerate {
        NSArray *array = @[
            @"Not Started",
            @"Running",
            @"Failed",
            @"Succeeded"
        ];
        return array;
    }

    + (TextOperationStatusCodes *) fromString: (NSString *) string {
        return (TextOperationStatusCodes *) string;
    }

    + (NSString *) toStringValue: (TextOperationStatusCodes *) value {
        return (NSString *) value;
    }

    /** Enum value Not Started. */
    static TextOperationStatusCodes* _NOT_STARTED = (TextOperationStatusCodes*)@"Not Started";

    + (TextOperationStatusCodes*) NOT_STARTED {
        return _NOT_STARTED;
    }

    /** Enum value Running. */
    static TextOperationStatusCodes* _RUNNING = (TextOperationStatusCodes*)@"Running";

    + (TextOperationStatusCodes*) RUNNING {
        return _RUNNING;
    }

    /** Enum value Failed. */
    static TextOperationStatusCodes* _FAILED = (TextOperationStatusCodes*)@"Failed";

    + (TextOperationStatusCodes*) FAILED {
        return _FAILED;
    }

    /** Enum value Succeeded. */
    static TextOperationStatusCodes* _SUCCEEDED = (TextOperationStatusCodes*)@"Succeeded";

    + (TextOperationStatusCodes*) SUCCEEDED {
        return _SUCCEEDED;
    }

@end
