/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import <Foundation/Foundation.h>

/**
 * Defines values for VisualFeatureTypes.
 */
@interface VisualFeatureTypes : NSString

    + (NSArray<VisualFeatureTypes*> *) enumerate;

    + (VisualFeatureTypes *) fromString: (NSString *) string;

    + (NSString *) toStringValue: (VisualFeatureTypes *) value;

    @property (class, readonly) VisualFeatureTypes* IMAGE_TYPE;

    @property (class, readonly) VisualFeatureTypes* FACES;

    @property (class, readonly) VisualFeatureTypes* ADULT;

    @property (class, readonly) VisualFeatureTypes* CATEGORIES;

    @property (class, readonly) VisualFeatureTypes* COLOR;

    @property (class, readonly) VisualFeatureTypes* TAGS;

    @property (class, readonly) VisualFeatureTypes* DESCRIPTION;

@end
